//
//  MoviesModels.swift
//  codeChallengeRappi
//
//  Created by Gerson Villanueva on 09/12/2018.
//  Copyright (c) 2018 rappi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Movies {
  // MARK: Use cases
    struct Request {
        var category: Categories
        var page: Int
    }
    
    struct Response {
        var movies: [Movie]
    }
    
    struct ViewModel {
        struct DisplayedMovie {
            var title: String?
            var posterPath: String?
            var releaseDate: Date?
            var overview: String?
        }
        
        var displayedMovies: [DisplayedMovie]
    }
}
