//
//  SearchWorker.swift
//  codeChallengeRappi
//
//  Created by Gerson Villanueva on 12/12/2018.
//  Copyright (c) 2018 rappi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchWorkerProtocol {
    func search(text: String, completion: @escaping ([Item]) -> Void, failure: @escaping (Error) -> Void)
}

class SearchWorker: SearchWorkerProtocol {
    
    func search(text: String, completion: @escaping ([Item]) -> Void, failure: @escaping (Error) -> Void) {
        SearchServices.getSearchResult(with: text, completion: { (items: [Item]) in
            completion(items)
        }) { (err: Error) in
            print(err)
        }
    }
}
