//
//  SearchPresenter.swift
//  codeChallengeRappi
//
//  Created by Gerson Villanueva on 12/12/2018.
//  Copyright (c) 2018 rappi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
  func presentItem(response: Search.Response)
}

class SearchPresenter: SearchPresentationLogic {
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
  func presentItem(response: Search.Response) {
    var itemModels = [Search.ViewModel.DisplayedItem]()
    for item in response.items {
        var itemModel = Search.ViewModel.DisplayedItem()
        itemModel.posterPath = item.posterPath
        itemModel.title = item.name
        itemModels.append(itemModel)
    }
    let viewModel = Search.ViewModel(displayedItems: itemModels)
    viewController?.displayItems(viewModel: viewModel)
  }
}
