//
//  SearchModels.swift
//  codeChallengeRappi
//
//  Created by Gerson Villanueva on 12/12/2018.
//  Copyright (c) 2018 rappi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  struct Request {
    var text: String
    var page: Int
  }
    
  struct Response {
    var items: [Item]
  }
    
  struct ViewModel {
    struct DisplayedItem {
        var title: String?
        var posterPath: String?
    }
    
    var displayedItems: [DisplayedItem]
  }
}
