//
//  SeriesPresenter.swift
//  codeChallengeRappi
//
//  Created by Gerson Villanueva on 11/12/2018.
//  Copyright (c) 2018 rappi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeriesPresentationLogic {
  func presentSeries(response: Series.Response)
}

class SeriesPresenter: SeriesPresentationLogic {
  weak var viewController: SeriesDisplayLogic?
  
  // MARK: Do something
  
    func presentSeries(response: Series.Response) {
        var serieModels = [Series.ViewModel.DisplayedSerie]()
        for serie in response.series {
            var serieModel = Series.ViewModel.DisplayedSerie()
            serieModel.title = serie.name
            serieModel.overview = serie.overview
            serieModel.posterPath = serie.posterPath
            serieModel.identifier = serie.serieId
            serieModels.append(serieModel)
        }
        let viewModel = Series.ViewModel(displayedSeries: serieModels)
        viewController?.displaySeries(viewModel: viewModel)
    }
}
